// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQuvdps8lO52G7SErv5dWdjKsbXJb2_Rs',
    appId: '1:459417840031:web:bd7fd3c5cebd8f3afbb5aa',
    messagingSenderId: '459417840031',
    projectId: 'iotproject-51bbb',
    authDomain: 'iotproject-51bbb.firebaseapp.com',
    databaseURL: 'https://iotproject-51bbb-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-51bbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZ70kdfXxfNwjy5upAeimKiKNkUC32v8',
    appId: '1:459417840031:android:013afb5a0d0e2edbfbb5aa',
    messagingSenderId: '459417840031',
    projectId: 'iotproject-51bbb',
    databaseURL: 'https://iotproject-51bbb-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-51bbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSWrTyte7O_7et01VwioW_t8SXed4mic',
    appId: '1:459417840031:ios:d31a1b165201efa6fbb5aa',
    messagingSenderId: '459417840031',
    projectId: 'iotproject-51bbb',
    databaseURL: 'https://iotproject-51bbb-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-51bbb.firebasestorage.app',
    iosBundleId: 'com.example.smartWater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvSWrTyte7O_7et01VwioW_t8SXed4mic',
    appId: '1:459417840031:ios:d31a1b165201efa6fbb5aa',
    messagingSenderId: '459417840031',
    projectId: 'iotproject-51bbb',
    databaseURL: 'https://iotproject-51bbb-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-51bbb.firebasestorage.app',
    iosBundleId: 'com.example.smartWater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQuvdps8lO52G7SErv5dWdjKsbXJb2_Rs',
    appId: '1:459417840031:web:5961c7e5fb45dd97fbb5aa',
    messagingSenderId: '459417840031',
    projectId: 'iotproject-51bbb',
    authDomain: 'iotproject-51bbb.firebaseapp.com',
    databaseURL: 'https://iotproject-51bbb-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-51bbb.firebasestorage.app',
  );

}